# This file was generated by GoReleaser. DO NOT EDIT.
cask "vaultr" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/vaultr"], must_succeed: false
    end
  end

  version "0.8.0"

  on_macos do
    on_arm do
      sha256 "fa6c9528510ebc4376eddff0f492c95e9f53df8b48880e9d7c72a2cd8a1b74d7"
      url "https://github.com/rnsc/vaultr/releases/download/v#{version}/vaultr_#{version}_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4d2f8ee82ba0bb5e4994b4eb1fdbd8de095ba30f0427511e92d5058329f2469a"
      url "https://github.com/rnsc/vaultr/releases/download/v#{version}/vaultr_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e270df49bf365a23ea6d9cdec785b0d7c387658c18565002aa7d9234ef86b652"
      url "https://github.com/rnsc/vaultr/releases/download/v#{version}/vaultr_#{version}_linux_amd64.tar.gz"
    end
  end

  name "vaultr"
  desc "Fast search over HashiCorp Vault KV paths and key names"
  homepage "https://github.com/rnsc/vaultr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vaultr"
  bash_completion "completions/vaultr.bash"
  fish_completion "completions/vaultr.fish"
  zsh_completion "completions/vaultr.zsh"

  # No zap stanza required
end
