# This file was generated by GoReleaser. DO NOT EDIT.
cask "vaultr" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/vaultr"], must_succeed: false
    end
  end

  version "0.8.1"

  on_macos do
    on_arm do
      sha256 "6b77a02d051910ab6368df9d3669a2162e0a5c5dfd4a107cce6a811615612b7b"
      url "https://github.com/rnsc/vaultr/releases/download/v#{version}/vaultr_#{version}_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2ce2a532b243551c7434712793bec02ae5facf32cd3cea3ced23d5a0367dee10"
      url "https://github.com/rnsc/vaultr/releases/download/v#{version}/vaultr_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "053ed56bff3f8e6cc1525c2a865d42decd98482d87b00c2a7cfc4642c0e9bed0"
      url "https://github.com/rnsc/vaultr/releases/download/v#{version}/vaultr_#{version}_linux_amd64.tar.gz"
    end
  end

  name "vaultr"
  desc "Fast search over HashiCorp Vault KV paths and key names"
  homepage "https://github.com/rnsc/vaultr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vaultr"
  bash_completion "completions/vaultr.bash"
  fish_completion "completions/vaultr.fish"
  zsh_completion "completions/vaultr.zsh"

  # No zap stanza required
end
