# This file was generated by GoReleaser. DO NOT EDIT.
cask "vaultr" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/vaultr"], must_succeed: false
    end
  end

  version "0.7.0"

  on_macos do
    on_arm do
      sha256 "2b46f3b8d0b25e27be07af2970a2477be688bad7562234860385883407bc05c1"
      url "https://github.com/rnsc/vaultr/releases/download/v#{version}/vaultr_#{version}_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "24966918ef1404ce9fe9d3213ab80cc0110ca74d0c09491b6714e8dbc51ed9ce"
      url "https://github.com/rnsc/vaultr/releases/download/v#{version}/vaultr_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d074de456c26f54c35d2e29ad219aa46f59d6a6fa38a451298908ed8adc7b358"
      url "https://github.com/rnsc/vaultr/releases/download/v#{version}/vaultr_#{version}_linux_amd64.tar.gz"
    end
  end

  name "vaultr"
  desc "Fast search over HashiCorp Vault KV paths and key names"
  homepage "https://github.com/rnsc/vaultr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vaultr"
  bash_completion "completions/vaultr.bash"
  fish_completion "completions/vaultr.fish"
  zsh_completion "completions/vaultr.zsh"

  # No zap stanza required
end
